export enum Category {
    FRONTEND = "FRONTEND",
    BACKEND = "BACKEND",
    FULL_STACK = "FULL_STACK",
    DEVOPS = "DEVOPS",
    MOBILE = "MOBILE",
    CLOUD = "CLOUD",
    AI = "AI",
    DATA_SCIENCE = "DATA_SCIENCE",
    COMPUTER_SCIENCE = "COMPUTER_SCIENCE",
    ARCHITECTURE = "ARCHITECTURE",
}