import { ConfidenceLevel } from "../../models/learningPath/enums/ConfidenceLevel";
import type { TopicDto } from "../../models/learningPath/TopicDto";

export const dummyTopics: TopicDto[] = [
    {
        id: "1",
        name: "JSX and React Components",
        description: "Learn JSX syntax, component composition, fragments, and how React renders component trees.",
        order: 1,
        confidenceLevel: ConfidenceLevel.HIGH,
        learningPathId: "1",
    },
    {
        id: "2",
        name: "Props and Component Communication",
        description: "Pass data between components, type props, use children, and design reusable component APIs.",
        order: 2,
        confidenceLevel: ConfidenceLevel.HIGH,
        learningPathId: "1",
    },
    {
        id: "3",
        name: "State and Event Handling",
        description: "Manage local state with useState and respond to user interactions through React events.",
        order: 3,
        confidenceLevel: ConfidenceLevel.MEDIUM,
        learningPathId: "1",
    },
    {
        id: "4",
        name: "Conditional Rendering and Lists",
        description: "Render dynamic interfaces with conditions, map collections into elements, and use stable keys.",
        order: 4,
        confidenceLevel: ConfidenceLevel.MEDIUM,
        learningPathId: "1",
    },
    {
        id: "5",
        name: "Forms and Controlled Inputs",
        description: "Build accessible forms, control input state, validate values, and handle form submissions.",
        order: 5,
        confidenceLevel: ConfidenceLevel.MEDIUM,
        learningPathId: "1",
    },
    {
        id: "6",
        name: "Effects and the Component Lifecycle",
        description: "Synchronize components with external systems using useEffect, dependencies, and cleanup functions.",
        order: 6,
        confidenceLevel: ConfidenceLevel.LOW,
        learningPathId: "1",
    },
    {
        id: "7",
        name: "Custom Hooks",
        description: "Extract reusable stateful logic into custom hooks with clear inputs and predictable outputs.",
        order: 7,
        confidenceLevel: ConfidenceLevel.LOW,
        learningPathId: "1",
    },
    {
        id: "8",
        name: "Context and Reducers",
        description: "Share state across the component tree with Context and manage complex transitions with useReducer.",
        order: 8,
        confidenceLevel: ConfidenceLevel.LOW,
        learningPathId: "1",
    },
    {
        id: "9",
        name: "Routing and Data Fetching",
        description: "Create client-side routes, load remote data, and handle loading, error, and empty states.",
        order: 9,
        confidenceLevel: ConfidenceLevel.LOW,
        learningPathId: "1",
    },
    {
        id: "10",
        name: "Performance and Testing",
        description: "Optimize rendering with memoization and verify component behavior using modern React testing practices.",
        order: 10,
        confidenceLevel: ConfidenceLevel.LOW,
        learningPathId: "1",
    },
];