import { Category } from "../../models/learningPath/enums/Category";
import { Difficulty } from "../../models/learningPath/enums/Difficulty";
import type { LearningPathDto } from "../../models/learningPath/LearningPathDto";

export const dummyData: LearningPathDto[] = [
    {
        id: "1",
        title: "React Development",
        description: "Master React fundamentals, hooks, state management, performance optimization, and modern frontend architecture.",
        completedTopicsCount: 0,
        totalSectionsCount: 0,
        totalTopicsCount: 10,
        createdAt: new Date(),
        category: Category.FRONTEND,
        difficulty: Difficulty.INTERMEDIATE,
    },
    {
        id: "2",
        title: "JavaScript Fundamentals",
        description: "Learn JavaScript core concepts including ES6+, asynchronous programming, DOM manipulation, and advanced patterns.",
        completedTopicsCount: 32,
        totalSectionsCount: 40,
        totalTopicsCount: 150,
        createdAt: new Date(),
        category: Category.FRONTEND,
        difficulty: Difficulty.BEGINNER,
    },
    {
        id: "3",
        title: "Spring Boot Backend",
        description: "Build production-ready backend applications with Spring Boot, REST APIs, security, JPA, and microservices.",
        completedTopicsCount: 15,
        totalSectionsCount: 35,
        totalTopicsCount: 200,
        createdAt: new Date(),
        category: Category.BACKEND,
        difficulty: Difficulty.ADVANCED,
    },
    {
        id: "4",
        title: "Node.js Backend",
        description: "Develop scalable backend applications using Node.js, Express, authentication, databases, and API design.",
        completedTopicsCount: 22,
        totalSectionsCount: 30,
        totalTopicsCount: 120,
        createdAt: new Date(),
        category: Category.BACKEND,
        difficulty: Difficulty.INTERMEDIATE,
    },
    {
        id: "5",
        title: "Docker & DevOps",
        description: "Understand containerization, Docker images, containers, networking, and deployment workflows.",
        completedTopicsCount: 8,
        totalSectionsCount: 20,
        totalTopicsCount: 80,
        createdAt: new Date(),
        category: Category.DEVOPS,
        difficulty: Difficulty.BEGINNER,
    },
];